#ifndef LV_CONF_H
#define LV_CONF_H

#define LV_COLOR_DEPTH 16
#define LV_MEM_CUSTOM 0
#define LV_MEM_SIZE (512U * 1024U)
#define LV_USE_LOG 1
#define LV_LOG_LEVEL LV_LOG_LEVEL_WARN
#define LV_LOG_PRINTF 1
#define LV_USE_PERF_MONITOR 0
#define LV_USE_LABEL 1
#define LV_USE_BTN 1
#define LV_USE_SLIDER 1
#define LV_USE_THEME_DEFAULT 1
#define LV_FONT_FMT_TXT_LARGE 1
#define LV_USE_FONT_COMPRESSED 1
#define LV_USE_PNG 1
#define LV_USE_FS_STDIO 1
#define LV_FS_STDIO_LETTER 'S'

#ifndef LV_USE_FREETYPE
#define LV_USE_FREETYPE 1
#endif

#if LV_USE_FREETYPE
#ifndef LV_FREETYPE_CACHE_SIZE
#define LV_FREETYPE_CACHE_SIZE (8 * 1024)
#endif
#ifndef LV_FREETYPE_SBIT_CACHE
#define LV_FREETYPE_SBIT_CACHE 1
#endif
#ifndef LV_FREETYPE_CACHE_FT_FACES
#define LV_FREETYPE_CACHE_FT_FACES 2
#endif
#ifndef LV_FREETYPE_CACHE_FT_SIZES
#define LV_FREETYPE_CACHE_FT_SIZES 4
#endif
#endif

#endif /* LV_CONF_H */
